(use srfi-42)

(define (good? pos queens)
  (not (find (^p (or (= (car p) (car pos))
                     (= (cdr p) (cdr pos))
                     (= (abs (- (car p) (car pos)))
                        (abs (- (cdr p) (cdr pos))))))
             queens)))

(define (solve)
  (let loop ((n 0)
             (queens ()))
    (if (= n 8)
        (display-board queens)
        (do-ec (:range i n 8)
               (:range j 8)
               (if (good? (cons i j) queens))
               (loop (+ n 1) (cons (cons i j) queens))))))

(define (display-board queens)
  (do-ec (: row 0 7)
         (let1 v (make-vector 8 #\.)
           (dolist (p queens)
             (if (= (car p) row)
                 (vector-set! v (cdr p) #\Q)))
           (print v)))
  (print))

(define (main args)
  (solve))
